### ISSUE TITLE
External compilation

### ISSUE THREAD

**Issue by cristeigabriel** [alpatov-softworks/avhook#3]
https://github.com/alpatov-softworks/avhook/blob/3be1752ae16e9380c9bcad2b4c78e46c4dd3aca3/CMakeLists.txt#L7

Here you can use DXSDK_DIR from path.

**Comment by VladislavAlpatov** [comment]
Fixed, thanks  for Issue
https://github.com/alpatov-softworks/avhook/commit/1666eb3e9a7c4425f5321042c581ca2067ff2180
